---
- name: check if the distribution is supported
  assert:
    that: 'ansible_distribution_release in role_krb5_supported_distributions'
    msg: "For this role, the distribution must be in {{ role_krb5_supported_distributions }}"
- name: ensure krb5-user and libpam-krb5 installation
  apt: name={{ item }} state=present install_recommends=no
  with_items:
    - krb5-user
    - libpam-krb5
- name: write krb5 config file /etc/krb5.conf
  template: src=krb5.conf.j2 dest=/etc/krb5.conf owner=root group=root mode='0644'


