---
# The data which describe the Sambaedu environment. These
# data must remain an _abstraction_ _layer_ independent of
# the role variables.

network:
  domain: 'athome.priv'
  ntp_servers:
    - '192.168.0.220'

samba:
  admin:
    login: 'Administrator'
    pwd: 'Administrator@123'
  fqdn: 'samba.athome.priv'

