---
- name: include settings variables
  hosts: '{{ target | default("all") }}'
  tasks:
    - include_vars:
        file: settings.yaml
        name: settings

- name: Linux clients Samba integration
  hosts: '{{ target | default("all") }}'
  vars:
    role_ntp_servers: '{{ settings.network.ntp_servers }}'
    role_krb5_realm: '{{ settings.network.domain | upper }}'
    role_sambamember_workgroup: '{{ settings.network.domain.split(".")[0] | upper }}'
    role_sambamember_realm: '{{ settings.network.domain | upper }}'
    role_sambamember_join_account: '{{ settings.samba.admin.login }}'
    role_sambamember_join_password: '{{ settings.samba.admin.pwd }}'
    role_sambamember_autojoin: '{{ autojoin | default(False) }}'
    #
    really_reboot: '{{ reboot | default(False) }}'
  roles:
    - 'ntp'
    - 'krb5'
    - 'sambamember'
    - 'dm'
    - { role: reboot, when: really_reboot  } # Must the last included role.


